insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Lygon Food Store', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Uni Square Cafe', 'Takeaway Food Services', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('French Lettuce', 'Takeaway Food Services', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Cafe Vista', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Degani Bakery Cafe', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('LeCirque', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Double Gauge', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Michels Pattiserie', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Bakehouse', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Hellens MacAulay Road Takeaway', 'Takeaway Food Services', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Aix Cafe Creperie Salon', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Diksteins Corner Bar', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Subway', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Vic Fish Licensed Cafe', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Shanghai Noodle House', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Sud', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Altitude', 'Pubs, Taverns and Bars', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Golden Monkey', 'Pubs, Taverns and Bars', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Madisons Restaurant Bar Lounge', 'Pubs, Taverns and Bars', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Breadtop', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Bread Top Bakery', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Little Cupcakes', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Japanese Cafe Hoya', 'Diet and Weight Reduction Centre Operation', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Japanese Cafe Hoya', 'Diet and Weight Reduction Centre Operation', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Tokio Japanese Take-Away', 'Takeaway Food Services', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Sushi Hut', 'Takeaway Food Services', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Toast Caffe', 'Catering Services', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Papa Guiseppe Pizza & Pasta', 'Takeaway Food Services', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Portside Deli', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('The Wharf Bakehouse', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('KFC', 'Takeaway Food Services', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Ootoro', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('181 Domain', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Cafe Domain', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Domain Brasserie', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Bacs', 'Cafes and Restaurants', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Cafe Fawkner', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('The Millswyn On Domain', 'Cafes and Restaurants', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Sate Plus', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Outdoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Sate Plus', 'Bakery Product Manufacturing (Non-factory based)', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('Royal Standard Hotel', 'Pubs, Taverns and Bars', 'Seats - Indoor');
insert into Restaurant (R_Name, Descrip, RT_Service) Values ('The Servery', 'Takeaway Food Services', 'Seats - Indoor');

