//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment_frez0003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int Resturent_id { get; set; }
        public int Customer_id { get; set; }
    
        public virtual Reg_Customer Reg_Customer { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
