//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment_frez0003.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5032_Assignment_DatabaseFirstEntities : DbContext
    {
        public FIT5032_Assignment_DatabaseFirstEntities()
            : base("name=FIT5032_Assignment_DatabaseFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Reg_Customer> Reg_Customer { get; set; }
        public virtual DbSet<Res_Owner> Res_Owner { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }

        public System.Data.Entity.DbSet<FIT5032_Assignment_frez0003.Models.Reg_Customer> Members { get; set; }
    }
}
