//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment_frez0003.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reg_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reg_Customer()
        {
            this.Bookings = new HashSet<Booking>();
        }
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Email must be filled up")]
        [EmailAddress(ErrorMessage ="Email is not valid, please provide proper email address")]
        [Display(Name = "Email Address")]
        public string C_Email { get; set; }
        [Required(ErrorMessage ="Password is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string C_Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("C_Password", ErrorMessage ="Please Confirm your password")]
        [Display(Name = "Confirm Password")]
        public string C_Confirm_Password { get; set;  }
        [Required(ErrorMessage = "First Name is required")]
        [Display(Name = "First Name")]
        public string CF_Name { get; set; }
        [Display(Name = "Last Name")]

        public string CL_Name { get; set; }
        [Required(ErrorMessage = "Phone Number is required")]
        [Display(Name = "Phone Number")]
        public int C_Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
