//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBankMelbourne_frez0003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust_Booking
    {
        public int Id { get; set; }
        public int Resturent_id { get; set; }
        public string Customer_id { get; set; }
        public System.DateTime Booking_Date_time { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
