//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBankMelbourne_frez0003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Comments
    {
        public int Id { get; set; }
        public string Cus_Init { get; set; }
        public string Com_String { get; set; }
        public Nullable<decimal> Com_Rate { get; set; }
        public int R_Id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
