//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBankMelbourne_frez0003.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Res_Comments
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Name")]
        public string Cus_Init { get; set; }
        [Required(ErrorMessage = "Please Enter your Comment")]
        [AllowHtml]
        public string Com_String { get; set; }
        [Range(0,5,ErrorMessage ="Enter Rating Between 0 to 5")]
        public Nullable<decimal> Com_Rate { get; set; }
        public int R_Id { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
