//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frez0003_FoodBank_Melb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reg_Customer()
        {
            this.Cust_Booking = new HashSet<Cust_Booking>();
        }
    
        public int Id { get; set; }
        public string C_Email { get; set; }
        public string C_Password { get; set; }
        public string CF_Name { get; set; }
        public string CL_Name { get; set; }
        public int C_Phone { get; set; }
        public string User_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cust_Booking> Cust_Booking { get; set; }
    }
}
